### ISSUE TITLE
The kernel analyzer ran successfully, but got an empty result!

### ISSUE THREAD

**Issue by 1120161891** [Markakd/GREBE#2]
![image](https://user-images.githubusercontent.com/38254882/179708871-3807212d-9e9c-4e54-aeee-9bcf10943667.png)

**Comment by Markakd** [comment]
Hey, would you minding including which report you are running on?

**Comment by De4dCr0w** [comment]
```
python3 run_analyze.py .
executing ~/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer --crash-report=./report --call-graph=./report_cg.txt ~/kernel/5.15/focal/lib/dump_stack.c.bc ~/kernel/5.15/focal/lib/dump_stack.c.bc ~/kernel/5.15/focal/mm/kasan/report.c.bc ~/kernel/5.15/focal/mm/kasan/report.c.bc ~/kernel/5.15/focal/mm/kasan/report.c.bc ~/kernel/5.15/focal/mm/kasan/generic.c.bc ~/kernel/5.15/focal/mm/kasan/generic.c.bc ~/kernel/5.15/focal/mm/kasan/shadow.c.bc ~/kernel/5.15/focal/fs/buffer.c.bc ~/kernel/5.15/focal/fs/buffer.c.bc ~/kernel/5.15/focal/block/bio.c.bc ~/kernel/5.15/focal/block/blk-core.c.bc ~/kernel/5.15/focal/block/blk-core.c.bc ~/kernel/5.15/focal/block/blk-mq.c.bc ~/kernel/5.15/focal/drivers/block/loop.c.bc ~/kernel/5.15/focal/block/blk-mq.c.bc ~/kernel/5.15/focal/block/blk-mq.c.bc ~/kernel/5.15/focal/kernel/softirq.c.bc ~/kernel/5.15/focal/kernel/softirq.c.bc ~/kernel/5.15/focal/kernel/softirq.c.bc ~/kernel/5.15/focal/kernel/smpboot.c.bc ~/kernel/5.15/focal/kernel/kthread.c.bc ~/kernel/5.15/focal/arch/x86/entry/entry_64.S.bc ~/kernel/5.15/focal/refcount.bc 

Total 24 file(s)
/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/lib/dump_stack.c.bc'
/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/lib/dump_stack.c.bc'
/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/mm/kasan/report.c.bc'
/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/mm/kasan/report.c.bc'
/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/mm/kasan/report.c.bc'
/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/mm/kasan/generic.c.bc'
/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/mm/kasan/generic.c.bc'
/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/mm/kasan/shadow.c.bc'
/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/fs/buffer.c.bc'
/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/fs/buffer.c.bc'
/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/block/bio.c.bc'
/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/block/blk-core.c.bc'
/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/block/blk-core.c.bc'
/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/block/blk-mq.c.bc'
/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/drivers/block/loop.c.bc'
/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/block/blk-mq.c.bc'
/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/block/blk-mq.c.bc'
/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/kernel/softirq.c.bc'
/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/kernel/softirq.c.bc'
/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/kernel/softirq.c.bc'
/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/kernel/smpboot.c.bc'
/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/kernel/kthread.c.bc'
/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/arch/x86/entry/entry_64.S.bc'
/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/refcount.bc'
inserting __dump_stack dump_stack_lvl
inserting dump_stack_lvl print_address_description
inserting print_address_description __kasan_report
inserting __kasan_report kasan_report
inserting kasan_report check_region_inline
inserting check_region_inline kasan_check_range
inserting kasan_check_range __kasan_check_write
inserting __kasan_check_write instrument_atomic_read_write
inserting instrument_atomic_read_write atomic_dec
inserting atomic_dec put_bh
inserting put_bh end_buffer_read_sync
inserting end_buffer_read_sync end_bio_bh_io_sync
inserting end_bio_bh_io_sync bio_endio
inserting bio_endio req_bio_endio
inserting req_bio_endio blk_update_request
inserting blk_update_request blk_mq_end_request
inserting blk_mq_end_request lo_complete_rq
inserting lo_complete_rq blk_complete_reqs
inserting blk_complete_reqs blk_done_softirq
inserting blk_done_softirq __do_softirq
inserting __do_softirq run_ksoftirqd
inserting run_ksoftirqd run_ksoftirqd
inserting run_ksoftirqd smpboot_thread_fn
inserting smpboot_thread_fn kthread
inserting kthread ret_from_fork
inserting ret_from_fork page:0000000002260fb8
Here is the crash location instrument_atomic_read_write include/linux/instrumented.h:101 explicit checking? 0
analyzer: /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/src/lib/CrashAnalyzer.cc:248: void CrashAnalyzer::dump(llvm::StringRef): Assertion `Ctx->TaintSrc.size() > 0 || Ctx->TmpTaintSrc.size() > 0' failed.
 #0 0x00000000005d7c6f llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer+0x5d7c6f)
 #1 0x00000000005d5ef2 llvm::sys::RunSignalHandlers() (/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer+0x5d5ef2)
 #2 0x00000000005d84e5 SignalHandler(int) (/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer+0x5d84e5)
 #3 0x00007f48208053c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x143c0)
 #4 0x00007f48202f403b raise /build/glibc-sMfBJT/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #5 0x00007f48202d3859 abort /build/glibc-sMfBJT/glibc-2.31/stdlib/abort.c:81:7
 #6 0x00007f48202d3729 get_sysdep_segment_value /build/glibc-sMfBJT/glibc-2.31/intl/loadmsgcat.c:509:8
 #7 0x00007f48202d3729 _nl_load_domain /build/glibc-sMfBJT/glibc-2.31/intl/loadmsgcat.c:970:34
 #8 0x00007f48202e5006 (/lib/x86_64-linux-gnu/libc.so.6+0x34006)
 #9 0x0000000000566123 CrashAnalyzer::dump(llvm::StringRef) /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/src/lib/CrashAnalyzer.cc:0:5
#10 0x0000000000565f18 CrashAnalyzer::dump() /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/src/lib/CrashAnalyzer.cc:233:1
#11 0x000000000053051a main /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/src/lib/KAMain.cc:269:16
#12 0x00007f48202d50b3 __libc_start_main /build/glibc-sMfBJT/glibc-2.31/csu/../csu/libc-start.c:342:3
#13 0x000000000052e96e _start (/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer+0x52e96e)
Stack dump:
0.	Program arguments: /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer --crash-report=./report --call-graph=./report_cg.txt /home/ddyy/kernel/5.15/focal/lib/dump_stack.c.bc /home/ddyy/kernel/5.15/focal/lib/dump_stack.c.bc /home/ddyy/kernel/5.15/focal/mm/kasan/report.c.bc /home/ddyy/kernel/5.15/focal/mm/kasan/report.c.bc /home/ddyy/kernel/5.15/focal/mm/kasan/report.c.bc /home/ddyy/kernel/5.15/focal/mm/kasan/generic.c.bc /home/ddyy/kernel/5.15/focal/mm/kasan/generic.c.bc /home/ddyy/kernel/5.15/focal/mm/kasan/shadow.c.bc /home/ddyy/kernel/5.15/focal/fs/buffer.c.bc /home/ddyy/kernel/5.15/focal/fs/buffer.c.bc /home/ddyy/kernel/5.15/focal/block/bio.c.bc /home/ddyy/kernel/5.15/focal/block/blk-core.c.bc /home/ddyy/kernel/5.15/focal/block/blk-core.c.bc /home/ddyy/kernel/5.15/focal/block/blk-mq.c.bc /home/ddyy/kernel/5.15/focal/drivers/block/loop.c.bc /home/ddyy/kernel/5.15/focal/block/blk-mq.c.bc /home/ddyy/kernel/5.15/focal/block/blk-mq.c.bc /home/ddyy/kernel/5.15/focal/kernel/softirq.c.bc /home/ddyy/kernel/5.15/focal/kernel/softirq.c.bc /home/ddyy/kernel/5.15/focal/kernel/softirq.c.bc /home/ddyy/kernel/5.15/focal/kernel/smpboot.c.bc /home/ddyy/kernel/5.15/focal/kernel/kthread.c.bc /home/ddyy/kernel/5.15/focal/arch/x86/entry/entry_64.S.bc /home/ddyy/kernel/5.15/focal/refcount.bc 
Aborted (core dumped)
Traceback (most recent call last):
  File "run_analyze.py", line 72, in <module>
    run_case(sys.argv[1])
  File "run_analyze.py", line 69, in run_case
    shutil.copyfile("/tmp/ca_result", case_path+"/sts.txt")
  File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ca_result'
```

Did you encounter such a problem?  How to run the kernel analyzer successfully ?

**Comment by 1120161891** [comment]
> ```
> python3 run_analyze.py .
> executing ~/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer --crash-report=./report --call-graph=./report_cg.txt ~/kernel/5.15/focal/lib/dump_stack.c.bc ~/kernel/5.15/focal/lib/dump_stack.c.bc ~/kernel/5.15/focal/mm/kasan/report.c.bc ~/kernel/5.15/focal/mm/kasan/report.c.bc ~/kernel/5.15/focal/mm/kasan/report.c.bc ~/kernel/5.15/focal/mm/kasan/generic.c.bc ~/kernel/5.15/focal/mm/kasan/generic.c.bc ~/kernel/5.15/focal/mm/kasan/shadow.c.bc ~/kernel/5.15/focal/fs/buffer.c.bc ~/kernel/5.15/focal/fs/buffer.c.bc ~/kernel/5.15/focal/block/bio.c.bc ~/kernel/5.15/focal/block/blk-core.c.bc ~/kernel/5.15/focal/block/blk-core.c.bc ~/kernel/5.15/focal/block/blk-mq.c.bc ~/kernel/5.15/focal/drivers/block/loop.c.bc ~/kernel/5.15/focal/block/blk-mq.c.bc ~/kernel/5.15/focal/block/blk-mq.c.bc ~/kernel/5.15/focal/kernel/softirq.c.bc ~/kernel/5.15/focal/kernel/softirq.c.bc ~/kernel/5.15/focal/kernel/softirq.c.bc ~/kernel/5.15/focal/kernel/smpboot.c.bc ~/kernel/5.15/focal/kernel/kthread.c.bc ~/kernel/5.15/focal/arch/x86/entry/entry_64.S.bc ~/kernel/5.15/focal/refcount.bc 
> 
> Total 24 file(s)
> /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/lib/dump_stack.c.bc'
> /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/lib/dump_stack.c.bc'
> /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/mm/kasan/report.c.bc'
> /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/mm/kasan/report.c.bc'
> /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/mm/kasan/report.c.bc'
> /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/mm/kasan/generic.c.bc'
> /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/mm/kasan/generic.c.bc'
> /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/mm/kasan/shadow.c.bc'
> /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/fs/buffer.c.bc'
> /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/fs/buffer.c.bc'
> /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/block/bio.c.bc'
> /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/block/blk-core.c.bc'
> /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/block/blk-core.c.bc'
> /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/block/blk-mq.c.bc'
> /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/drivers/block/loop.c.bc'
> /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/block/blk-mq.c.bc'
> /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/block/blk-mq.c.bc'
> /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/kernel/softirq.c.bc'
> /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/kernel/softirq.c.bc'
> /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/kernel/softirq.c.bc'
> /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/kernel/smpboot.c.bc'
> /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/kernel/kthread.c.bc'
> /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/arch/x86/entry/entry_64.S.bc'
> /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer: error loading file '/home/ddyy/kernel/5.15/focal/refcount.bc'
> inserting __dump_stack dump_stack_lvl
> inserting dump_stack_lvl print_address_description
> inserting print_address_description __kasan_report
> inserting __kasan_report kasan_report
> inserting kasan_report check_region_inline
> inserting check_region_inline kasan_check_range
> inserting kasan_check_range __kasan_check_write
> inserting __kasan_check_write instrument_atomic_read_write
> inserting instrument_atomic_read_write atomic_dec
> inserting atomic_dec put_bh
> inserting put_bh end_buffer_read_sync
> inserting end_buffer_read_sync end_bio_bh_io_sync
> inserting end_bio_bh_io_sync bio_endio
> inserting bio_endio req_bio_endio
> inserting req_bio_endio blk_update_request
> inserting blk_update_request blk_mq_end_request
> inserting blk_mq_end_request lo_complete_rq
> inserting lo_complete_rq blk_complete_reqs
> inserting blk_complete_reqs blk_done_softirq
> inserting blk_done_softirq __do_softirq
> inserting __do_softirq run_ksoftirqd
> inserting run_ksoftirqd run_ksoftirqd
> inserting run_ksoftirqd smpboot_thread_fn
> inserting smpboot_thread_fn kthread
> inserting kthread ret_from_fork
> inserting ret_from_fork page:0000000002260fb8
> Here is the crash location instrument_atomic_read_write include/linux/instrumented.h:101 explicit checking? 0
> analyzer: /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/src/lib/CrashAnalyzer.cc:248: void CrashAnalyzer::dump(llvm::StringRef): Assertion `Ctx->TaintSrc.size() > 0 || Ctx->TmpTaintSrc.size() > 0' failed.
>  #0 0x00000000005d7c6f llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer+0x5d7c6f)
>  #1 0x00000000005d5ef2 llvm::sys::RunSignalHandlers() (/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer+0x5d5ef2)
>  #2 0x00000000005d84e5 SignalHandler(int) (/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer+0x5d84e5)
>  #3 0x00007f48208053c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x143c0)
>  #4 0x00007f48202f403b raise /build/glibc-sMfBJT/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
>  #5 0x00007f48202d3859 abort /build/glibc-sMfBJT/glibc-2.31/stdlib/abort.c:81:7
>  #6 0x00007f48202d3729 get_sysdep_segment_value /build/glibc-sMfBJT/glibc-2.31/intl/loadmsgcat.c:509:8
>  #7 0x00007f48202d3729 _nl_load_domain /build/glibc-sMfBJT/glibc-2.31/intl/loadmsgcat.c:970:34
>  #8 0x00007f48202e5006 (/lib/x86_64-linux-gnu/libc.so.6+0x34006)
>  #9 0x0000000000566123 CrashAnalyzer::dump(llvm::StringRef) /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/src/lib/CrashAnalyzer.cc:0:5
> #10 0x0000000000565f18 CrashAnalyzer::dump() /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/src/lib/CrashAnalyzer.cc:233:1
> #11 0x000000000053051a main /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/src/lib/KAMain.cc:269:16
> #12 0x00007f48202d50b3 __libc_start_main /build/glibc-sMfBJT/glibc-2.31/csu/../csu/libc-start.c:342:3
> #13 0x000000000052e96e _start (/home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer+0x52e96e)
> Stack dump:
> 0.	Program arguments: /home/ddyy/kernel-fuzz/workdir/GREBE/analyzer/build/lib/analyzer --crash-report=./report --call-graph=./report_cg.txt /home/ddyy/kernel/5.15/focal/lib/dump_stack.c.bc /home/ddyy/kernel/5.15/focal/lib/dump_stack.c.bc /home/ddyy/kernel/5.15/focal/mm/kasan/report.c.bc /home/ddyy/kernel/5.15/focal/mm/kasan/report.c.bc /home/ddyy/kernel/5.15/focal/mm/kasan/report.c.bc /home/ddyy/kernel/5.15/focal/mm/kasan/generic.c.bc /home/ddyy/kernel/5.15/focal/mm/kasan/generic.c.bc /home/ddyy/kernel/5.15/focal/mm/kasan/shadow.c.bc /home/ddyy/kernel/5.15/focal/fs/buffer.c.bc /home/ddyy/kernel/5.15/focal/fs/buffer.c.bc /home/ddyy/kernel/5.15/focal/block/bio.c.bc /home/ddyy/kernel/5.15/focal/block/blk-core.c.bc /home/ddyy/kernel/5.15/focal/block/blk-core.c.bc /home/ddyy/kernel/5.15/focal/block/blk-mq.c.bc /home/ddyy/kernel/5.15/focal/drivers/block/loop.c.bc /home/ddyy/kernel/5.15/focal/block/blk-mq.c.bc /home/ddyy/kernel/5.15/focal/block/blk-mq.c.bc /home/ddyy/kernel/5.15/focal/kernel/softirq.c.bc /home/ddyy/kernel/5.15/focal/kernel/softirq.c.bc /home/ddyy/kernel/5.15/focal/kernel/softirq.c.bc /home/ddyy/kernel/5.15/focal/kernel/smpboot.c.bc /home/ddyy/kernel/5.15/focal/kernel/kthread.c.bc /home/ddyy/kernel/5.15/focal/arch/x86/entry/entry_64.S.bc /home/ddyy/kernel/5.15/focal/refcount.bc 
> Aborted (core dumped)
> Traceback (most recent call last):
>   File "run_analyze.py", line 72, in <module>
>     run_case(sys.argv[1])
>   File "run_analyze.py", line 69, in run_case
>     shutil.copyfile("/tmp/ca_result", case_path+"/sts.txt")
>   File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
>     with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ca_result'
> ```
> 
> 你遇到过这样的问题吗？如何成功运行内核分析器？

I have also encountered such a problem. The reason for the error is that the bitcode file failed to load, and you may not have compiled the kernel source code correctly. After compiling with LLVM provided by the author, it can run successfully without error, but the result cannot be obtained.

**Comment by De4dCr0w** [comment]
I have compiled with LLVM provided by the author, and I compiled the kernel source code with "make CC=clang -j10 LLVM_IAS=0". Is it right? Could you provide the compile command for me?

**Comment by 1120161891** [comment]
> 我是用作者提供的LLVM编译的，我用“make CC=clang -j10 LLVM_IAS=0”编译内核源代码。这样对吗？你能给我提供编译命令吗？

Sorry, I don't have an experimental environment to provide compilation commands. It is worth noting that clang-11 is used to compile kernel source code, and clang-10 is used to build analyzer. How can I reach you? We can communicate kernel security more conveniently.

**Comment by De4dCr0w** [comment]
> > 我是用作者提供的LLVM编译的，我用“make CC=clang -j10 LLVM_IAS=0”编译内核源代码。这样对吗？你能给我提供编译命令吗？
> 
> Sorry, I don't have an experimental environment to provide compilation commands. It is worth noting that clang-11 is used to compile kernel source code, and clang-10 is used to build analyzer. How can I reach you? We can communicate kernel security more conveniently.

You can find my email in my github.

**Comment by De4dCr0w** [comment]
> > 我是用作者提供的LLVM编译的，我用“make CC=clang -j10 LLVM_IAS=0”编译内核源代码。这样对吗？你能给我提供编译命令吗？
> 
> Sorry, I don't have an experimental environment to provide compilation commands. It is worth noting that clang-11 is used to compile kernel source code, and clang-10 is used to build analyzer. How can I reach you? We can communicate kernel security more conveniently.

师傅编译的是哪个内核版本，我这还是报这个错误

**Comment by Markakd** [comment]
Hey guys, thanks for the discussion.

I am sorry for the late response.

@De4dCr0w You have to use the same version of clang to build both kernel and analyzer.

**Comment by De4dCr0w** [comment]
> Hey guys, thanks for the discussion.
> 
> I am sorry for the late response.
> 
> @De4dCr0w You have to use the same version of clang to build both kernel and analyzer.

But you clearly provide two versions of clang to build kernel and analyzer  in the instructions for use.  I'm confused.

**Comment by Markakd** [comment]
> > Hey guys, thanks for the discussion.
> > I am sorry for the late response.
> > @De4dCr0w You have to use the same version of clang to build both kernel and analyzer.
> 
> But you clearly provide two versions of clang to build kernel and analyzer in the instructions for use. I'm confused.

You're right, let me adjust the readme.

**Comment by ShengWu00** [comment]
@Markakd @De4dCr0w @1120161891 Sorry to interrupt, do you know how to compile Linux kernel to get all required bitcode files? I compiled kernel as following:
```
make CC="/path/to/clang" defconfig
make CC="/path/to/clang" kvm_guest.config
make CC="/path/to/clang" olddefconfig

make CC="/path/to/clang" -j$(nproc)
```
However, I didn't get all the bitcode files, and here's the analysis info:
```
executing ~/GREBE/analyzer/build/lib/analyzer --crash-report=./case/report --call-graph=./case/report_cg.txt ./case/linux-bitcode/lib/list_debug.c.bc ./case/linux-bitcode/crypto/algapi.c.bc ./case/linux-bitcode/crypto/pcrypt.c.bc ./case/linux-bitcode/crypto/pcrypt.c.bc ./case/linux-bitcode/crypto/algboss.c.bc ./case/linux-bitcode/kernel/kthread.c.bc ./case/linux-bitcode/arch/x86/entry/entry_64.S.bc 

Total 7 file(s)
/home/ws/GREBE/analyzer/build/lib/analyzer: error loading file './case/linux-bitcode/lib/list_debug.c.bc'
/home/ws/GREBE/analyzer/build/lib/analyzer: error loading file './case/linux-bitcode/crypto/pcrypt.c.bc'
/home/ws/GREBE/analyzer/build/lib/analyzer: error loading file './case/linux-bitcode/crypto/pcrypt.c.bc'
/home/ws/GREBE/analyzer/build/lib/analyzer: error loading file './case/linux-bitcode/arch/x86/entry/entry_64.S.bc'
inserting __list_del_entry_valid __list_del_entry
inserting __list_del_entry list_del
inserting list_del crypto_drop_spawn
inserting crypto_drop_spawn crypto_drop_aead
inserting crypto_drop_aead pcrypt_create_aead
inserting pcrypt_create_aead pcrypt_create
inserting pcrypt_create cryptomgr_probe
inserting cryptomgr_probe kthread
inserting kthread ret_from_fork
Here is the crash location __list_del_entry_valid lib/list_debug.c:51 explicit checking? 1
analyzer: /home/ws/GREBE/analyzer/src/lib/CrashAnalyzer.cc:248: void CrashAnalyzer::dump(llvm::StringRef): Assertion `Ctx->TaintSrc.size() > 0 || Ctx->TmpTaintSrc.size() > 0' failed.
 #0 0x00000000005d57ff llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/home/ws/GREBE/analyzer/build/lib/analyzer+0x5d57ff)
 #1 0x00000000005d3a82 llvm::sys::RunSignalHandlers() (/home/ws/GREBE/analyzer/build/lib/analyzer+0x5d3a82)
 #2 0x00000000005d6075 SignalHandler(int) (/home/ws/GREBE/analyzer/build/lib/analyzer+0x5d6075)
 #3 0x00007ff1fd922420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x00007ff1fd41100b raise /build/glibc-SzIz7B/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #5 0x00007ff1fd3f0859 abort /build/glibc-SzIz7B/glibc-2.31/stdlib/abort.c:81:7
 #6 0x00007ff1fd3f0729 get_sysdep_segment_value /build/glibc-SzIz7B/glibc-2.31/intl/loadmsgcat.c:509:8
 #7 0x00007ff1fd3f0729 _nl_load_domain /build/glibc-SzIz7B/glibc-2.31/intl/loadmsgcat.c:970:34
 #8 0x00007ff1fd401fd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
 #9 0x0000000000563d83 CrashAnalyzer::dump(llvm::StringRef) /home/ws/GREBE/analyzer/src/lib/CrashAnalyzer.cc:0:5
#10 0x0000000000563b78 CrashAnalyzer::dump() /home/ws/GREBE/analyzer/src/lib/CrashAnalyzer.cc:233:1
#11 0x000000000052e50a main /home/ws/GREBE/analyzer/src/lib/KAMain.cc:269:16
#12 0x00007ff1fd3f2083 __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:342:3
#13 0x000000000052c95e _start (/home/ws/GREBE/analyzer/build/lib/analyzer+0x52c95e)
Stack dump:
0.	Program arguments: /home/ws/GREBE/analyzer/build/lib/analyzer --crash-report=./case/report --call-graph=./case/report_cg.txt ./case/linux-bitcode/lib/list_debug.c.bc ./case/linux-bitcode/crypto/algapi.c.bc ./case/linux-bitcode/crypto/pcrypt.c.bc ./case/linux-bitcode/crypto/pcrypt.c.bc ./case/linux-bitcode/crypto/algboss.c.bc ./case/linux-bitcode/kernel/kthread.c.bc ./case/linux-bitcode/arch/x86/entry/entry_64.S.bc 
Aborted (core dumped)
Traceback (most recent call last):
  File "run_analyze.py", line 68, in <module>
    run_case(sys.argv[1])
  File "run_analyze.py", line 65, in run_case
    shutil.copyfile("/tmp/ca_result", case_path+"/sts.txt")
  File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ca_result'
```
